export const COUNTRY_SEED = [
  { code: 'DE', name: 'Germany', priority: 100 },
  { code: 'AT', name: 'Austria', priority: 95 },
  { code: 'CH', name: 'Switzerland', priority: 95 },
  { code: 'NL', name: 'Netherlands', priority: 90 },
  { code: 'BE', name: 'Belgium', priority: 90 },
  { code: 'FR', name: 'France', priority: 88 },
  { code: 'IT', name: 'Italy', priority: 88 },
  { code: 'ES', name: 'Spain', priority: 88 },
  { code: 'PT', name: 'Portugal', priority: 84 },
  { code: 'PL', name: 'Poland', priority: 84 },
  { code: 'CZ', name: 'Czechia', priority: 82 },
  { code: 'DK', name: 'Denmark', priority: 80 },
  { code: 'SE', name: 'Sweden', priority: 80 },
  { code: 'NO', name: 'Norway', priority: 78 },
  { code: 'FI', name: 'Finland', priority: 78 },
  { code: 'GB', name: 'United Kingdom', priority: 78 },
  { code: 'IE', name: 'Ireland', priority: 74 },
  { code: 'LU', name: 'Luxembourg', priority: 72 },
  { code: 'US', name: 'United States', priority: 70 },
  { code: 'CA', name: 'Canada', priority: 66 },
  { code: 'AE', name: 'United Arab Emirates', priority: 64 },
  { code: 'TR', name: 'Turkey', priority: 62 },
]

export const CITY_SEED = [
  { id: 'de-berlin', countryCode: 'DE', name: 'Berlin', region: 'Berlin', slug: 'berlin', population: 3669491 },
  { id: 'de-hamburg', countryCode: 'DE', name: 'Hamburg', region: 'Hamburg', slug: 'hamburg', population: 1852478 },
  { id: 'de-munich', countryCode: 'DE', name: 'Munich', region: 'Bavaria', slug: 'munich', population: 1488202 },
  { id: 'de-cologne', countryCode: 'DE', name: 'Cologne', region: 'North Rhine-Westphalia', slug: 'cologne', population: 1085664 },
  { id: 'de-frankfurt', countryCode: 'DE', name: 'Frankfurt am Main', region: 'Hesse', slug: 'frankfurt-am-main', population: 763380 },
  { id: 'de-stuttgart', countryCode: 'DE', name: 'Stuttgart', region: 'Baden-Wuerttemberg', slug: 'stuttgart', population: 635911 },
  { id: 'de-dusseldorf', countryCode: 'DE', name: 'Duesseldorf', region: 'North Rhine-Westphalia', slug: 'duesseldorf', population: 620523 },
  { id: 'de-leipzig', countryCode: 'DE', name: 'Leipzig', region: 'Saxony', slug: 'leipzig', population: 593145 },
  { id: 'de-dortmund', countryCode: 'DE', name: 'Dortmund', region: 'North Rhine-Westphalia', slug: 'dortmund', population: 588250 },
  { id: 'de-essen', countryCode: 'DE', name: 'Essen', region: 'North Rhine-Westphalia', slug: 'essen', population: 582415 },
  { id: 'de-bremen', countryCode: 'DE', name: 'Bremen', region: 'Bremen', slug: 'bremen', population: 567559 },
  { id: 'de-dresden', countryCode: 'DE', name: 'Dresden', region: 'Saxony', slug: 'dresden', population: 556780 },
  { id: 'de-hanover', countryCode: 'DE', name: 'Hanover', region: 'Lower Saxony', slug: 'hanover', population: 534049 },
  { id: 'de-nuremberg', countryCode: 'DE', name: 'Nuernberg', region: 'Bavaria', slug: 'nuernberg', population: 518365 },
  { id: 'de-duisburg', countryCode: 'DE', name: 'Duisburg', region: 'North Rhine-Westphalia', slug: 'duisburg', population: 495885 },
  { id: 'de-bochum', countryCode: 'DE', name: 'Bochum', region: 'North Rhine-Westphalia', slug: 'bochum', population: 364920 },
  { id: 'de-bonn', countryCode: 'DE', name: 'Bonn', region: 'North Rhine-Westphalia', slug: 'bonn', population: 330579 },
  { id: 'de-muenster', countryCode: 'DE', name: 'Muenster', region: 'North Rhine-Westphalia', slug: 'muenster', population: 316403 },
  { id: 'de-karlsruhe', countryCode: 'DE', name: 'Karlsruhe', region: 'Baden-Wuerttemberg', slug: 'karlsruhe', population: 308436 },
  { id: 'de-mannheim', countryCode: 'DE', name: 'Mannheim', region: 'Baden-Wuerttemberg', slug: 'mannheim', population: 309721 },
  { id: 'de-augsburg', countryCode: 'DE', name: 'Augsburg', region: 'Bavaria', slug: 'augsburg', population: 296582 },
  { id: 'de-wiesbaden', countryCode: 'DE', name: 'Wiesbaden', region: 'Hesse', slug: 'wiesbaden', population: 278474 },
  { id: 'de-freiburg', countryCode: 'DE', name: 'Freiburg im Breisgau', region: 'Baden-Wuerttemberg', slug: 'freiburg-im-breisgau', population: 231195 },
  { id: 'de-potsdam', countryCode: 'DE', name: 'Potsdam', region: 'Brandenburg', slug: 'potsdam', population: 182112 },
  { id: 'at-vienna', countryCode: 'AT', name: 'Vienna', region: 'Vienna', slug: 'vienna', population: 1911191 },
  { id: 'at-salzburg', countryCode: 'AT', name: 'Salzburg', region: 'Salzburg', slug: 'salzburg', population: 155416 },
  { id: 'ch-zurich', countryCode: 'CH', name: 'Zurich', region: 'Zurich', slug: 'zurich', population: 434335 },
  { id: 'ch-geneva', countryCode: 'CH', name: 'Geneva', region: 'Geneva', slug: 'geneva', population: 203951 },
  { id: 'nl-amsterdam', countryCode: 'NL', name: 'Amsterdam', region: 'North Holland', slug: 'amsterdam', population: 872680 },
  { id: 'nl-rotterdam', countryCode: 'NL', name: 'Rotterdam', region: 'South Holland', slug: 'rotterdam', population: 651446 },
  { id: 'fr-paris', countryCode: 'FR', name: 'Paris', region: 'Ile-de-France', slug: 'paris', population: 2165423 },
  { id: 'es-madrid', countryCode: 'ES', name: 'Madrid', region: 'Community of Madrid', slug: 'madrid', population: 3223334 },
  { id: 'it-milan', countryCode: 'IT', name: 'Milan', region: 'Lombardy', slug: 'milan', population: 1366180 },
  { id: 'gb-london', countryCode: 'GB', name: 'London', region: 'England', slug: 'london', population: 8982000 },
  { id: 'us-new-york', countryCode: 'US', name: 'New York', region: 'New York', slug: 'new-york', population: 8804190 },
  { id: 'ae-dubai', countryCode: 'AE', name: 'Dubai', region: 'Dubai', slug: 'dubai', population: 3331400 },
]
